name: Track

# Controls when the workflow will run
on:
  push:
    branches:
      - deploy
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *' # every 30min

jobs:
  arweave-tracking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: deploy
      - uses: actions/setup-python@v3
      - run: pip install -r requirements.txt
      - run: python . start_tracking --keep_tracking --keep_recent_count 10000
      - name: Check Git Status
        id: status
        run: '[[ -z $(git status -s) ]] || echo "::set-output name=status::changed"'
      - name: Commit && Push
        if: steps.status.outputs.status == 'changed'
        run: |
          git config --global user.name 'Arweave Tracker'
          git config --global user.email 'crysheen+arweave-tracker@gmail.com'
          git add .
          git commit -am "Update data"
          git push origin deploy
